routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => 'locolize'], function()
{
    Route::get('/search-price', 'IndexController@searchPrice')->name('search.price');
    Route::get('/search', 'IndexController@search')->name('search');

    Route::get('/local/local', 'IndexController@local')->name('nurik');

    Route::get('/share/{type}/{url}', function($type, $url, $title) {
        return Share::load($url, $title)->services($type);
    })->name('share');
    Route::get('/packagess', 'IndexController@packages')->name('packages');
    Route::get('/old', 'IndexController@home')->name('home.old');
    Route::get('/', 'IndexController@homeNew')->name('home');
    Route::get('/doctors', 'IndexController@doctors')->name('doctors');
    Route::get('/history', 'IndexController@history')->name('history');
    Route::get('/doctors/{docSlug}', 'IndexController@doctor')->name('doctor');


    Route::get('/packagess/{packSlug}', 'IndexController@package')->name('package');


    Route::get('/checks', 'IndexController@checks')->name('checks');
    Route::get('/price', 'IndexController@price')->name('price');

    Route::get('/news', 'IndexController@news')->name('news');
    Route::get('/news/{postSlug}', 'IndexController@post')->name('post');

    Route::get('/carier', 'IndexController@carier')->name('carier');

    Route::get('/departments', 'IndexController@departments')->name('departments');
    Route::get('/departments/{depSlug}', 'IndexController@department')->name('department');
    Route::get('/gallery', 'IndexController@gallery')->name('gallery');
    Route::get('{page}/{subs?}', ['uses' => 'IndexController@index'])
        ->where(['page' => '^((?!admin).)*$', 'subs' => '.*']);

    Route::post('/phone-form', 'IndexController@phoneForm')->name('form.phone');
    Route::post('/simple-form', 'IndexController@simpleForm')->name('form.simple');




    Route::post('/fixed-form', 'IndexController@fixedForm')->name('form.fixed');
});




Route::group(['prefix' => config('backpack.base.route_prefix'), 'middleware' => ['admin'], 'namespace' => 'Admin'], function()
{
   CRUD::resource('department', 'DepartmentCrudController');
   CRUD::resource('doctor', 'DoctorCrudController');
   CRUD::resource('gallery', 'GalleryCrudController');
   CRUD::resource('package', 'PackageCrudController');
   CRUD::resource('post', 'PostCrudController');
   CRUD::resource('price', 'PriceCrudController');
   CRUD::resource('review', 'ReviewCrudController');
   CRUD::resource('sale', 'SaleCrudController');
   CRUD::resource('slider', 'SliderCrudController');
   CRUD::resource('specialization', 'SpecializationCrudController');
   CRUD::resource('check', 'CheckCrudController');
   CRUD::resource('history', 'HistoryCrudController');
   CRUD::resource('setting', 'SettingCrudController');
   CRUD::resource('vacancy', 'VacancyCrudController');

});

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Backpack\CRUD\CrudTrait;
use Cviebrock\EloquentSluggable\Sluggable;
use Jenssegers\Date\Date;
use Nicolaslopezj\Searchable\SearchableTrait;
use Backpack\CRUD\ModelTraits\SpatieTranslatable\HasTranslations;

class Post extends Model
{
    use CrudTrait;
    use Sluggable;
    use SearchableTrait;
    use HasTranslations;

    /*
    |--------------------------------------------------------------------------
    | GLOBAL VARIABLES
    |--------------------------------------------------------------------------
    */

    protected $table = 'posts';
    // protected $primaryKey = 'id';
    // public $timestamps = false;
    // protected $guarded = ['id'];
    protected $fillable = ['title', 'content', 'slug', 'image', 'active'];
    public $translatable = ['title', 'content'];
    // protected $hidden = [];
    // protected $dates = [];

    /*
    |--------------------------------------------------------------------------
    | FUNCTIONS
    |--------------------------------------------------------------------------
    */

    protected $searchable = [
        'columns' => [
            'posts.title' => 10,
            'posts.content' => 10
        ]
    ];

    public function sluggable()
    {
        return [
            'slug' => [
                'source' => 'slug_or_title',
            ],
        ];
    }

    /*
    |--------------------------------------------------------------------------
    | RELATIONS
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | SCOPES
    |--------------------------------------------------------------------------
    */

    /*
    |--------------------------------------------------------------------------
    | ACCESORS
    |--------------------------------------------------------------------------
    */
    public function getSlugOrTitleAttribute()
    {
        if ($this->slug != '') {
            return $this->slug;
        }

        return $this->title;
    }

    /*
    |--------------------------------------------------------------------------
    | MUTATORS
    |--------------------------------------------------------------------------
    */
    public function setImageAttribute($value)
    {
        $attribute_name = "image";
        $disk = "uploads";
        $destination_path = "news";

        // if the image was erased
        if ($value==null) {
            // delete the image from disk
            \Storage::disk($disk)->delete($this->{$attribute_name});

            // set null in the database column
            $this->attributes[$attribute_name] = null;
        }

        // if a base64 was sent, store it in the db
        if (starts_with($value, 'data:image'))
        {
            // 0. Make the image
            $image = \Image::make($value);
            $image->resize(300, null, function ($constraint) {
                $constraint->aspectRatio();
            });
            // 1. Generate a filename.
            $filename = md5($value.time()).'.png';
            // 2. Store the image on disk.
            \Storage::disk($disk)->put($destination_path.'/'.$filename, $image->stream());
            // 3. Save the path to the database
            $this->attributes[$attribute_name] = $destination_path.'/'.$filename;
        }
    }

    public function getCreatedAtAttribute($value) {
        return Date::parse($value)->format('j F Y');
    }
}

resources/views/pages/news/index.blade.php
@extends('master') 

@section('content')
<main role="main">
    <div class="container category-container news-1-1">
        <div class="row category-row">
            <div class="col-sm-6 desc">
                <div class="container">
                    <div class="album packets news-1">
                        <div class="row">
                            <div class="container packs-overlay">

                                <h1>{{ $post->title }}</h1>
                            <p class="small">{{ $post->created_at }}</p>

                                {!! $post->content !!}
                            </div>
                        <img src="{{ asset('uploads/' . $post->image) }}">
                        </div>
                    </div>
                <img class="del-line" width="100%" src="{{ asset('images/Line%209.png') }}">

                    <!--<div class="row social">
                        <div class="col-sm-6 heading">
                            <p>Поделиться с друзьями:</p>
                        </div>
                        <div class="col-sm-6 icons">
                            <div class="row">
                                <div class="col-sm-3">
                                    <a href="">
                                    <img src="{{ asset('images/facebook.png') }}">
                                    </a>
                                </div>
                                <div class="col-sm-3">
                                    <a href="">
                                        <img src="{{ asset('images/twitter.png') }}">
                                    </a>
                                </div>
                                <div class="col-sm-3">
                                    <a href="">
                                        <img src="{{ asset('images/vkontakte-logo.png') }}">
                                    </a>
                                </div>
                                <div class="col-sm-3">
                                    <a href="">
                                        <img src="{{ asset('images/odnoklassniki-logo.png') }}">
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>-->

                    <div class="row ">
                        <div class="zvonok">
                            <h3 class="zakaz-headers">По всем вопросам звоните:</h3>
                            <p class="zakaz-text"> 220-70-70, 292-67-56, 293-08-77, 239-07-03, 293-09-66, +7- 777-300-00-03, 292-37-40 (бухгалтерия)</p>
                            <form id="zakaz-form" action="{{ route('form.phone') }}" method="post">
                                    {{ csrf_field() }}
                                <h3 class="zakaz-headers">Или закажите обратный звонок:</h3>
                                <input type="text" class="input-zvon" placeholder="Введите свой телефон" name="phone">
                                <input type="submit" id="zakazat" name="zvonok" value="Заказать">
                            </form>
                        </div>
                    </div>

                    <!--<div class="row review comm">
                        <div class="container">
                            <div class="row">

                                <h2 class="">Оставить комментарий</h2>
                            </div>

                            <br>
                            <form class="forma-otzyv" action="" method="post">
                                <div class="row">
                                    <div class="col-sm-6">
                                        <input class="base-info" type="text" placeholder="Введите имя">

                                    </div>
                                    <div class="col-sm-6">
                                        <input class="base-info second" type="text" placeholder="Введите свой Email">

                                    </div>
                                </div>

                                <br>
                                <div class="row otzyv-attach">

                                    <textarea placeholder="Оставьте свой отзыв"></textarea>


                                </div>
                                <div class="row both">
                                    <div class="col-sm-6 files">
                                        <input type="file" name="file" id="file" class="inputfile">
                                        <label for="file">Выбрать</label>
                                        <div class="txt-label">
                                            <span id="label-text">Прикрепить файл</span>
                                        </div>
                                    </div>
                                    <div class="col-sm-6 files">
                                        <input type="submit" id="makeReg" value="Оставить отзыв">
                                    </div>
                                </div>
                            </form>
                        </div>
                    </div>-->

                </div>
            </div>


            <div class="col-sm-6 sidebar news-1-side">

                <div class="container">
					@foreach($news as $post)
                    <div class="row">
                        <a href="{{ route('post', ['postSlug' => $post->slug]) }}">
                            <p>{{ $post->title }}</p>
                        </a>
                        <p class="small text-muted">{{ $post->created_at }}</p>
                    </div>
					@endforeach
                    
                </div>

            </div>
        </div>
    </div>
</main>
@endsection

@section('css')
<link rel="stylesheet" href="{{ asset('css/stylesheet.css') }}">

@endsection

resources/views/pages/news/news.blade.php
@extends('master') 

@section('content')
<main role="main">
    <div class="container news">
        <h1 class="news-heading">Новости</h1>
        @foreach($news->chunk(4) as $items)
        <div class="row news-rows">
            @foreach($items as $item)
            <div class="col-sm-3 @if($loop->last) last @endif">
                <a href="{{ route('post', ['postSlug' => $item->slug]) }}">
                    <img src="{{ asset('uploads/' . $item->image) }}">
                </a>
                <div class="caption">
                <p class="small text-muted">{{ $item->created_at }}</p>
                <a href="{{ route('post', ['postSlug' => $item->slug]) }}">
                        <p class="medium">{{ $item->title }}</p>
                    </a>
                </div>
            </div>
            @endforeach
        </div>
        @endforeach
        <div class="pagination">
   
			{{ $news->links('partials.pagination') }}


        
            {{-- <a href="#">
                <img src="images/Group%2030.png">
            </a>
            <a href="#">1</a>
            <a class="active" href="#">2</a>
            <a href="#">3</a>
            <a href="#">4</a>
            <a href="#">5</a>
            <a href="#">6</a>
            <a href="#">
                <img src="images/Group%2032.png">
            </a> --}}
        </div>
    </div>


    <img class="del-line2" width="750.84" src="images/Line%209.png">

    {{-- <div class="row social news-soc">
        <div class="col-sm-6 heading2">
            <p>Поделиться с друзьями:</p>
        </div>
        <div class="col-sm-6 icons2">
            <div class="row">
                <div class="col-sm-3">
                    <a href="">
                        <img src="images/facebook.png">
                    </a>
                </div>
                <div class="col-sm-3">
                    <a href="">
                        <img src="images/twitter.png">
                    </a>
                </div>
                <div class="col-sm-3">
                    <a href="">
                        <img src="images/vkontakte-logo.png">
                    </a>
                </div>
                <div class="col-sm-3">
                    <a href="">
                        <img src="images/odnoklassniki-logo.png">
                    </a>
                </div>
            </div>
        </div>
    </div> --}}

    <div class="row news-zvon">
        <div class="zvonok2">
            <div class="row ">
                <div class="col-sm-6">
                    <h3 class="zakaz-headers2">По всем вопросам звоните:</h3>
                    <p class="zakaz-text"> 220-70-70, 292-67-56, 293-08-77, 239-07-03, 293-09-66, +7- 777-300-00-03, 292-37-40 (бухгалтерия)</p>
                </div>
                <div class="col-sm-6">
                        <form id="zakaz-form" action="{{ route('form.phone') }}" method="post">
                                {{ csrf_field() }}
                        <h3 class="zakaz-headers2">Или закажите обратный звонок:</h3>
                        <input type="text" class="input-zvon2" placeholder="Введите свой телефон" name="phone">
                        <input type="submit" id="zakazat2" name="zvonok" value="Заказать">
                    </form>
                </div>
            </div>
        </div>
    </div>

</main>
@endsection
@section('css')
<link rel="stylesheet" href="{{ asset('css/stylesheet.css') }}">

@endsection